global using FluentValidation;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using TrackHubRouter.Domain.Interfaces.Operator;
global using Common.Domain.Enums;
global using TrackHubRouter.Domain.Interfaces;
global using TrackHubRouter.Domain.Interfaces.Manager;
global using Common.Application.Interfaces;
global using TrackHubRouter.Domain.Interfaces.Registry;
